SELECT NAME, DBID FROM V$DATABASE;
-- List your backup

1. SHUTDOWN IMMEDIATE;
2. DELETE CONTROLLFILE
3. START NOMOUNT
3. RESTORE CONTROLFILE FROM 'F:\app\Tungn\virtual\product\12.2.0\dbhome_1\database\CF_D-ORCL_ID-1547000808_1CUF4GOH';